### ISSUE TITLE
shub importing non-existent stuff

### ISSUE THREAD

**Issue by seandavi** [singularityhub/singularity-python#29]
Looks like the shub script is perhaps mismatched relative to the rest of the code.  I am getting import errors related to at least "build_spec" and "singularity.docker".

**Comment by vsoch** [comment]
yes this is correct! Right now singurity-python is optimized to drive the builders for singularity-hub [primarily here](https://github.com/singularityware/singularity-python/blob/master/singularity/build.py) and a lot of the viewing functions are (at least temporarily) integrated directly into singularity-hub so there isn't redundancy (eg, [see here](https://singularity-hub.org/containers/8/view). My plan is this break to remove the redundant functionality, but I'd be really interested to hear about your desired use case, and that will better help to move the direction of the software! This thread or the other is good - let's leave this issue open until I fix the missing imports.

**Comment by vsoch** [comment]
ok, day 1 of work is complete, so the command line util is updated (to remove these errors). There is still more testing to be done with regard to the builders, but the executable is back to functioning, so I'm going to close this issue.
