### ISSUE TITLE
add singularity containers to boutiques spec

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularity-python#6]
[see here](https://github.com/boutiques/tools/issues/22)

The boutiques spec is (currently, under development) using the boutiques spec to carry very simple info about inputs. If we have a proper field for the containers themselves, and perhaps the url on singularity hub, it would be meaningful for singularity hub to provide a (boutiques descriptor) of the container, for usage in other applications. This makes sense to test/do once we have the hub up and running, and can give containers index/urls, etc.

**Comment by glatard** [comment]
Description in Boutiques issue was moved there: https://github.com/boutiques/schema/issues/45

**Comment by vsoch** [comment]
For now, I'm removing boutques spec, because it hasn't been properly discussed how (or if) we want to store this level of detail. If/when the need comes, we can create a new issue / re-open to discuss.
