### ISSUE TITLE
run_client.py faild to pull an image, with "Do you have permission to write to ..." error message

### ISSUE THREAD

**Issue by alaindomissy** [singularityhub/singularity-python#64]
STEPS TO RECREATE:

# Create a conda environment in which I pip installed singularity-python:
`
conda create -n shub-1.1.8 python=2.7
source activate shub-1.1.8
pip install singularity
`

#  In order to download from singularity-hub.org the image:  alaindomissy/rnaseqtools ,
#  Create and run a script as follows:
`
# create a target directory for download with full permissions
mkdir DOWNLOADS
chmod +777 DOWNLOADS

# create the following script,  based on 
# https://github.com/singularityware/singularity-python/blob/master/examples/shub/run_client.py

cat > ~/DOWNLOADS/shub_pull.py <<'EOSCRIPT'
#!/usr/bin/python2
from __future__ import print_function
from singularity.hub.client import Client

shub = Client()    
container_name = 'alaindomissy/rnaseqtools'
collection = shub.get_collection(container_name)
container_ids = collection['container_set']
container_id = container_ids.pop()
print("container_id:", container_id)
manifest = shub.get_container(container_id)
image = shub.pull_container(manifest)

EOSCRIPT

# make executable
chmod +x ~/DOWNLOADS/shub_pull.py

# run it
cd DOWNLOADS
./shub_pull.py

`
This is the error I get:
ERROR:shub_builder:Error downloading https://www.googleapis.com/download/storage/v1/b/singularity-hub-regional/o/singularity-hub-regional%2Fgithub.com%2Falaindomissy%2Frnaseqtools%2Fe173a79b008e7aa3a51301da19328b63aa799b1e%2F42acf3dd57b3570816289ca532352acf.img.gz?generation=1494864381960279&alt=media. Do you have permission to write to /home/adomissy/DOWNLOADS?

NOTE: modifying the script so that the download goes to /tmp instead works:
chnaging the last line of the script to :
image = shub.pull_container(manifest,  download_folder='/tmp')

These are the permission on tmp:
ls -ld /tmp
drwxrwxrwt 299 root root 2527232 May 15 19:19 /tmp

And these are the permissions on ~/DOWNLOADS
ll -d DOWNLOADS/
drwxrwxrwx 2 adomissy yeo-group 3 May 15 19:08 DOWNLOADS/

Thanks!

**Comment by vsoch** [comment]
heyo! The one bug I ran into when testing this is that, even though you install to conda, you are actually using /usr/bin/python2 as the interpreter, because the header of the script is like:

```
#!/usr/bin/python2
```
and you don't execute it with the python binary directly --> `./run_client.py`

Just for sanity's check - could you try changing the interpreter to be environment python 2, like:

```
!#/usr/bin/env python2
```

and then call it with the conda install directly, which is probably something like:

```
/home/adomissy/anaconda2/bin/python run_client.py
```
I want to make sure this still reproduces the error, because I couldn't get it to work when I had the wrong python / script header, and then when I specified these things it seemed to work ok.

In summary I did:

 - change header to be environment python
 - install singularity to anaconda 2 (using /anaconda2/bin/pip)
-  call run_client directly with anaconda2 python

then I see:

```
/home/vanessa/anaconda2/bin/python2 run_client.py 
Environment message level found to be DEBUG
DEBUG:shub_builder:Headers found: Content-Type
INFO:shub_builder:User: alaindomissy
INFO:shub_builder:Repo Name: rnaseqtools
INFO:shub_builder:Repo Tag: latest
DEBUG:shub_builder:GET https://singularity-hub.org/api/collection/alaindomissy/rnaseqtools:latest
DEBUG:shub_builder:Headers found: Content-Type
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): singularity-hub.org
DEBUG:requests.packages.urllib3.connectionpool:https://singularity-hub.org:443 "GET /api/collection/alaindomissy/rnaseqtools:latest HTTP/1.1" 200 None
('container_id:', 911)
INFO:shub_builder:Numeric image ID 911 found.
DEBUG:shub_builder:GET https://singularity-hub.org/api/containers/911
DEBUG:shub_builder:Headers found: Content-Type
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): singularity-hub.org
DEBUG:requests.packages.urllib3.connectionpool:https://singularity-hub.org:443 "GET /api/containers/911 HTTP/1.1" 301 None
DEBUG:requests.packages.urllib3.connectionpool:https://singularity-hub.org:443 "GET /api/containers/911/ HTTP/1.1" 200 None
INFO:shub_builder:Singularity Hub Image: alaindomissy-rnaseqtools-master.img.gz
Found image alaindomissy/rnaseqtools:master
Downloading image... alaindomissy-rnaseqtools-master.img.gz
DEBUG:shub_builder:GET https://www.googleapis.com/download/storage/v1/b/singularity-hub-regional/o/singularity-hub-regional%2Fgithub.com%2Falaindomissy%2Frnaseqtools%2Fe173a79b008e7aa3a51301da19328b63aa799b1e%2F42acf3dd57b3570816289ca532352acf.img.gz?generation=1494864381960279&alt=media
DEBUG:shub_builder:Headers found: Content-Type
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com
DEBUG:requests.packages.urllib3.connectionpool:https://www.googleapis.com:443 "GET /download/storage/v1/b/singularity-hub-regional/o/singularity-hub-regional%2Fgithub.com%2Falaindomissy%2Frnaseqtools%2Fe173a79b008e7aa3a51301da19328b63aa799b1e%2F42acf3dd57b3570816289ca532352acf.img.gz?generation=1494864381960279&alt=media HTTP/1.1" 200 1697683702
Decompressing alaindomissy-rnaseqtools-master.img.gz
```

If the error persists after this, we can dig in a big more! Apologies for taking some time to get back to this, I got sort of back logged this evening... not even started home yet!

**Comment by vsoch** [comment]
@alaindomissy is this still an issue for you?
