### ISSUE TITLE
run_client.py fails - with apparent permission issue - to pull image into folder even with 777 permissions

### ISSUE THREAD

**Issue by alaindomissy** [singularityhub/singularity-python#65]
### Create a conda environment in which I pip installed singularity-python:
`conda create -n shub-1.1.8 python=2.7`
`source activate shub-1.1.8`
`pip install singularity`

### To download the alaindomissy/rnaseqtools image from singularity-hub.org create and run a script as follows:
```
# create a target directory for download with full permissions
`mkdir DOWNLOADS`
`chmod +777 DOWNLOADS`

# create the following script,  based on 
# https://github.com/singularityware/singularity-python/blob/master/examples/shub/run_client.py

```cat > ~/DOWNLOADS/shub_pull.py <<'EOSCRIPT'
#!/usr/bin/python2
from __future__ import print_function
from singularity.hub.client import Client

shub = Client()    
container_name = 'alaindomissy/rnaseqtools'
collection = shub.get_collection(container_name)
container_ids = collection['container_set']
container_id = container_ids.pop()
print("container_id:", container_id)
manifest = shub.get_container(container_id)
image = shub.pull_container(manifest)

EOSCRIPT

# make executable
chmod +x ~/DOWNLOADS/shub_pull.py

# run it
cd DOWNLOADS
./shub_pull.py
```

### This is the error I get:

`ERROR:shub_builder:Error downloading https://www.googleapis.com/download/storage/v1/b/singularity-hub-regional/o/singularity-hub-regional%2Fgithub.com%2Falaindomissy%2Frnaseqtools%2Fe173a79b008e7aa3a51301da19328b63aa799b1e%2F42acf3dd57b3570816289ca532352acf.img.gz?generation=1494864381960279&alt=media. Do you have permission to write to /home/adomissy/DOWNLOADS?`
`

#### changing the last line of the script to :
`image = shub.pull_container(manifest,  download_folder='/tmp')`

#### these are the permission on tmp:
`ls -ld /tmp`
`drwxrwxrwt 299 root root 2527232 May 15 19:19 /tmp`

#### and these are the permissions on ~/DOWNLOADS
`ls -ld DOWNLOADS/`
`drwxrwxrwx 2 adomissy yeo-group 3 May 15 19:08 DOWNLOADS/`

Thanks!

**Comment by vsoch** [comment]
hey this looks like it might be the same issue as with #64 - give the suggestions a test run and let me know if they fix it up!

**Comment by vsoch** [comment]
ping @alaindomissy !
