### ISSUE TITLE
support to create symlink in repos linked to singularityhub?

### ISSUE THREAD

**Issue by pescobar** [singularityhub/singularity-python#79]
Hi,

I tried to link this github repo to singularity hub
https://github.com/pescobar/netgen

which created this collection
https://www.singularity-hub.org/collections/138

I first created the repo with a single file `Singularity.5.3.1` and I noticed that I couldn't pull `latest` from the hub. To solve it I created a symlink in the repo `Singularity >> Singularity.5.3.1` so tag `latest` points to `5.3.1` but after doing it I get this error in the hub build log

```
DEBUG Spec file for build should be in /tmp/tmph0ng9drl/Singularity
ERROR Return Code 1: b'\x1b[31mERROR: Unsupported file type: /tmp/tmph0ng9drl/Singularity
\x1b(B\x1b[mCleaning up...
```

A workaround would be to duplicate the file `Singularity.5.3.1` in the repo with the name `Singularity` but I think it would be nicer to support following symlinks as I prefer to avoid code duplication as much as possible. 

Or maybe there is any better solution for this that I am missing?

**Comment by vsoch** [comment]
This has been fixed for the builder - if it's not present in the dev version it will be soon with the release of 2.4.1. Thanks @pescobar ! I'm going to close because if I don't now I'll forget about it later. If there is issue, after the 2.4.1 release, please open in the singularityhub repo.
