### ISSUE TITLE
Update PyPi package to be in sync with version used by sregistry (or later?)

### ISSUE THREAD

**Issue by dtrudg** [singularityhub/singularity-python#87]
Had a weird error where `sregistry push` was failing to our sregistry server, due to a timestamp timezone mismatch issue between timestamp sent by client on our cluster and computed by the sregistry server. Initially replaced `timezone.now()` with `timezone.utcnow()` everywhere for a hacky, but guaranteed fix for an impending demo.

Noted eventually that we we had a pip-installed version of singularity-python in-use which is from Oct 23rd, while `singularityhub/sregistry` is using an Oct 30th specific commit in its requirements.txt - in between there was a change to the timestamp creation.

Would be great if the PyPi package can be updated, so anyone using sregisty with the pip installed singularity-python has consistent timestamp creation functions in use.

**Comment by vsoch** [comment]
I think probably what we want to do here is to remove the singularity python dependency entirely, and this was my plan for the next version of singularity-python (that will have the entire sregistry module removed as it is now installed from github.com/singularityhub/sregistry-cli. Once it's removed then we can update the pip. But would the removal of the dependency from sregistry help in the meantime?

**Comment by dtrudg** [comment]
I guess removal of the dep would help in weird cases such as I arrived at.

I'm just a little concerned that sregistry-cli looks a bit heavy - needs SQLalchemy etc. vs current stuff in singularity-python. Is there a way I can download an sregistry image programatically using it without creating a sqlite database etc? Thinking about CI and scripting that pulls images to run security checks etc. - guess I can use `singularity pull` though.

**Comment by vsoch** [comment]
I think the currently (only) requirement for the base sregistry is the SQLalchemy, and I did this based on the assumption that the entire desire was to have a local manager. It is a valid use case to just want to "move stuff around" bits and not the storage. Hmm, I wonder how we could do that - for install there could be a pip install for each of the requirements that is called `base` that doesn't install the storage, eg:

```
pip install sregistry[registry-base]
```
and then the client would do two things - disable the storage either if the user has disabled it via the environment, or if the database modules just don't load.

If I test this out with a branch, would you be able to test?

**Comment by dtrudg** [comment]
I'd be happy to test - yes.

**Comment by vsoch** [comment]
okay great! I put this together quickly, it likely has a bug here and there, but it's important to get something down quick because then we can move it quickly! https://github.com/singularityhub/sregistry-cli/pull/55
